[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "ISC", "MIT", "MPL-2.0"]
confidence-threshold = 1.0
private = { ignore = true }

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.exceptions]]
allow = ["OpenSSL"]
crate = "ring"

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
crate = "unicode-ident"
